development:
  stripe_secret_key: 'pk_test_No16rSXOYAdhbccFumtsILu300xRTOrfbU'
  stripe_publishable_key: 'sk_test_327i6VnfLzFLlkUj0elCxTco005vknis1x'

production:
  stripe_secret_key: 'pk_test_No16rSXOYAdhbccFumtsILu300xRTOrfbU'
  stripe_publishable_key: 'sk_test_327i6VnfLzFLlkUj0elCxTco005vknis1x'